### ISSUE TITLE
(温度検知) データを処理する

### ISSUE THREAD

**Issue by sse01-14** [Smart-SE/sse2018-group2#10]

**Comment by kh1r0** [comment]
#8で取得したデータを閾値判定し、
#11で温度がぬるくなったことを通知する

**Comment by kh1r0** [comment]
データの取得と通知
http://tech.toreta.in/entry/2016/02/15/153203

**Comment by ot20161114** [comment]
考慮事項
①飲料自体の温度は測れない（水没できない）ので、ジョッキ・グラス温度越しに推測するか？
②季節・室温を考慮するか？

参考：
https://detail.chiebukuro.yahoo.co.jp/qa/question_detail/q1199520066
https://tanoshiiosake.jp/2324

**Comment by sse01-14** [comment]
@kh1r0 
#7 
https://github.com/Smart-SE/sse2018-group2/tree/master/Uematsu(S)
↑でcsv出力イメージ置いて頂いているので、こちらご参照頂いて進められそうでしょうか？

**Comment by sse01-10** [comment]
発表しながらデモするって考えると、実際に温度が変わり始めるのにラグがあるので
@sse01-14 さんの案
＞片方は常温、片方は冷やした状態で、センサ差し替えて疑似的にぬるくなった状態を再現する感じかなと思ってます。
が良さそうですね。

理想を言えば、リアルタイムで温度をグラフ表示できて、閾値を超えたら
タブレットないしスマホに通知される。ってのが見せれるとGoodですよね
(やろうと思えばこれまたIFTTT使ってwebhookであらかじめグラフ設定しておいたGoogle Sheetに追加可能です）

**Comment by kh1r0** [comment]
対応が遅くなりましてすいません。
以下の場所に温度判定処理(プロトタイプ)を登録しました。
https://github.com/Smart-SE/sse2018-group2/tree/master/hkoba

**Comment by ot20161114** [comment]
ありがとうございます。拝見いたしました。皆さんでレビューします？

（今今、構成上気になった点）
・「データ取得」「データ処理」は、
①intervalが違うので、別プロセス？
②intervalが違うが、親がmain.pyの子プロセス？
③intervalを一緒にして、main.pyからwhile内で順次それぞれ呼び出し？

・print("over limit")のところが、LineNotifyになるイメージ？

**Comment by sse01-14** [comment]
@kh1r0 さん、コード作成ありがとうございます！

@ot20161114  さん、ご確認ありがとうございます。最終的なIntegrationどうするかってとこですね。別プロセスにしておいた方がサービス化段階でどんな実装パターンになったとしても適用し易そうですが、デモの段階では③が早くて分かり易いのか。

**Comment by ot20161114** [comment]
Integration、、、跨る場合は、各TASKはクローズして、
新たに作った方がよいでしょうか（発表用調整のような少し大きい括りで）？

**Comment by kh1r0** [comment]
みなさんご確認いただきありがとうございます。
詳細は詰めきれていませんでした。。。

デモの段階で使用するかわかりませんが、
DBへデータを保存する処理も書いてみました。

https://github.com/Smart-SE/sse2018-group2/tree/master/hkoba

よろしくお願いします。

**Comment by ot20161114** [comment]
ありがとうございます。私の方で、マージ版を作成してみます。
少々お待ちください（ライブラリは最終的に「requirements.txt」を起こせばよいかと思います。
ところで、pandasってラズパイに入りますっけ？Anaconda環境でしか使った事がなく、、、）

**Comment by ot20161114** [comment]
> ありがとうございます。私の方で、マージ版を作成してみます。
> 少々お待ちください（ライブラリは最終的に「requirements.txt」を起こせばよいかと思います。
> ところで、pandasってラズパイに入りますっけ？Anaconda環境でしか使った事がなく、、、）

pip不可。
「sudo apt-get install python3-pandas」or
「sudo apt-get install python-pandas」
→OSのライブラリとしてインストール。

**Comment by sse01-14** [comment]
完了！
