### ISSUE TITLE
(温度検知・レコメンド通知) データ処理コンポーネントとタブレット間のIF・通信方法の決定

### ISSUE THREAD

**Issue by sse01-14** [Smart-SE/sse2018-group2#11]

**Comment by sse01-10** [comment]
想定される送信データ
　ジョッキID
　"温度上昇"
タイムスタンプはタブレット側？？

**Comment by sse01-14** [comment]
データ処理コンポーネントがどの程度の範囲をカバーするかの決めが今のところないですが、例えば店舗全体のジョッキをカバーする（そこから各ジョッキがあるテーブルの各タブレットにデータを送る）ケースを想定すると、タブレット側で処理した方が負荷や通信量の観点で良いかもしれないですね。そもそもそんなに負荷かかるような使い方でなければ気にしなくても良いのでしょうが。

**Comment by sse01-14** [comment]
今日の講義後ちょっと詰めましょうか。あと一週間なので、、、前後の工程ご担当頂いている、
@kh1r0 
@atsuematsu 
さんと、あとセンサから値取るところも含めてだと
@sse01-10 
さん辺りで話せれば決まりますかね？

**Comment by sse01-10** [comment]
すみません、16:30から30分~45分程度修了制作の打ち合わせがあります。
間に合わなければ決まったことをWikiへ記載していただけると助かります。

**Comment by ot20161114** [comment]
私（奥田）の方も、修了制作打合せがありますが、時間があれば、参加致します。
ご連絡としては、
①残量検知は、明日、明後日にショップ（秋月あたり）に行って、店員に聞きながら物品
手配しようかと思います（自費で構いません）。ついてに欲しいものがあれば、お知らせ
下さい。
②（アジャイルの授業なので）Projectsのページにカンバンツールがありました。登録され
ているテンプレ別に３つ作ってありますので、利用してみて下さい（私は使い方がまだわか
っておりません）
③（アジャイルの授業なので）obnizeで試しに作った温度検知をリポに登録してもよいで
しょうか？それから、無理そうなので、別の方法を探ったという（イテレーションを回した
）というストーリーで。

**Comment by sse01-14** [comment]
@sse01-10 
@ot20161114 
はい、その他諸々決めた方が良いことある気がするので、初めに上記の議論してその後の時間で合流できれば他の点も議論しましょう。

@ot20161114 
③、良いと思います！

**Comment by sse01-14** [comment]
部屋の利用可能時間を超過して出なければいけず、、、後ほどアップデートします。ざっくり言うと一台のラズパイで全部やっちゃいましょう、という結論に至りました。

**Comment by ot20161114** [comment]
ありがとうございます。以下については、如何でしょうか？
①タブレットは準備可能でしょうか？
②LINE通知案もありましたが、タブレットにはインストールできましたっけ？SIM有りでないと無理でしょうか？無理なら、従業員のモバイルに通知でしょうか？

私はSIM無しiPadなら、ありますので試してみます。

**Comment by ot20161114** [comment]
ipadに、LINE準備できました（固定電話の番号で認証）。pythonから通知すると考えると、LINE Notifyでしょうか？

**Comment by sse01-10** [comment]
準備ありがとうございます。
LINE連携がちと面倒なので出来ればURLを参考に実装していただきたいです。

IFTTT、最近知りましたけどめっちゃ便利なのでオススメです。
https://mimimopu.com/raspberry-pi_line/

サンプルコードも作っておきました。
https://github.com/Smart-SE/sse2018-group2/blob/master/Uematsu(S)/FromWebhookToLine.py

**Comment by ot20161114** [comment]
ありがとうございます（私も、そのページ見ていました）。試してみます。
main.py的には、
TemperatureModule.pyで値取得
FileModule.pyでファイル出力
（～で閾値判定）
要通知なら、FromWebhookToLine.pyのLineNotifyキックでしょうか？

**Comment by sse01-14** [comment]
おおっ、こんな方法があるんですね・・・勉強になります。

温度検知の方は土曜日の議論で、Raspberry pi上でWebサーバ稼働させ、レコメンドをブラウザ表示させるような形で進めて頂いています。デモとしてはRaspberry pi上ないしはノートPCからWebサーバにブラウザ経由でアクセスして表示させれば良いかなという想定です。（タブレットまでは用意しないが、タブレットがあればWebブラウザ起動できれば同じことが再現できるので、それで良いかなと）

LINE通知は卓上タブレットに表示させるというよりも、店員のハンディターミナル（って言うんですかね？オーダー入力用の端末です）に「〇番テーブルにオーダー伺いに行ってください！」みたいなメッセージを送るイメージで使うのが良いかなと思いましたがいかがでしょうかね？最近はiPhoneをそのままハンディターミナルとして使っている飲食店もあるので（直感的に操作がわかるのでその方が学生バイトとかも使い方を覚え易いのだとか）、そこに通知するイメージです。デモ段階でどう見せるかは検討必要かもしれませんが、そこまでできるとかなり良い仕上がりに見せられそうです！

**Comment by sse01-14** [comment]
#22 にアップしている発表資料ドラフトからの抜粋ですが、こちらのデモ時の実装イメージにLINE通知を追加しますかね。
![01_](https://user-images.githubusercontent.com/43286856/45955109-0479bc80-c04a-11e8-9ba6-ff80a81697e5.png)
![02_](https://user-images.githubusercontent.com/43286856/45955111-06438000-c04a-11e8-8f53-332801d252b9.png)

**Comment by sse01-14** [comment]
あ、画像をアップするとそのまま表示できるんですね。便利。

**Comment by sse01-10** [comment]
@ot20161114 
そうですね。今回は1台のラズパイで温度取得からデータ処理、通知までを行うって事なので
mainに追記していく形がいいかと思います。
（ファイル分割については何かルールがあるのかも知れませんが理解できていないため
一応機能ごとに分けたつもりです。）

とここまで書いたんですが
@sse01-14 
土曜日の段階でブラウザ表示案が出ているようですね。
IFTTT利用はブラウザ表示案の出来次第な感じもしますが、
どんな感じでしょう？（打ち合わせ参加できておらず申し訳ございません）

**Comment by ot20161114** [comment]
>IFTTT利用はブラウザ表示案の出来次第な感じもしますが、
>どんな感じでしょう？（打ち合わせ参加できておらず申し訳ございません）

~~同じくです。
ちなみに、LINE端末/IFTTTアカ、ご用意できる方おられますでしょうか？~~

ipadで良い事になったので準備してみます。

**Comment by sse01-14** [comment]
> IFTTT利用はブラウザ表示案の出来次第な感じもしますが、
> どんな感じでしょう？（打ち合わせ参加できておらず申し訳ございません）

土曜日に確認させてもらった段階ではRaspberry pi上でWebサーバとDBはそのまま使えそうですねくらいの確認だったので、進捗は #12 の方で確認させてもらえればと思います。とは言えそれはそれで、LINE通知もできます、と言うのが見せられるならより良いかなと。

**Comment by ot20161114** [comment]
通知飛びました。イベントネームとトークンは記載のものでお願い致します（長くて見づらくなったらHideしてくださいませ）。
~~~python
#!/usr/bin/python
# -*- coding: utf-8 -*-

import requests
from datetime import datetime
import sys

#ここへEvent名を入れる
EVENT_NAME = 'raspberry_pi'
#ここへ、Webhookのキーを入れる。
IFTTT_KEY = 'c0n2tYjtjCbaYwZYXBMjyG'
IFTTT_FROM_WEBHOOK_TO_LINE = 'https://maker.ifttt.com/trigger/'+EVENT_NAME+'/with/key/'

#Line側の設定をデフォルトのまま使えば下記関数でそのまま利用可能
def LineNotify(time, valueA, valueB):
	requests.post(IFTTT_FROM_WEBHOOK_TO_LINE + IFTTT_KEY, json = {"value1":time, "value2":valueA, "value3":valueB})

if __name__ == '__main__':
    argv = sys.argv

    LineNotify(datetime.now().strftime("%Y/%m/%d %H:%M:%S"),argv[1],'温くなっています')
~~~

`python ./FromWebhookToLine.py 10`で起動

![img_0131](https://user-images.githubusercontent.com/36760280/46109285-18c0e380-c21b-11e8-8ca4-9d9417f578df.PNG)

![img_0132](https://user-images.githubusercontent.com/36760280/46109316-2bd3b380-c21b-11e8-8651-7c087c95c3e2.PNG)

**Comment by sse01-14** [comment]
おおー、良い！！デモは画面あると説得力増しますね～

**Comment by ot20161114** [comment]
スタンプ（sticker）も！など思いましたが、グループ３と、もろ被りしそうな気がしておりまして、
オリジナル画像など表示させる等考慮した方がよいでしょうか。
参考：https://engineering.linecorp.com/ja/blog/detail/94

もしくは、Googel Homeに喋らせるとか。。。
参考：https://chasuke.com/ghnotifier/

まあ、別にコンペでもないとは思うのですが。WEBができてれば（lineは補助）。
ただ、テキストline通知のみだと厳しいかなと思った次第です。

お酒の席も色々あるかと思いますが、どう通知してくれると、嬉しいのでしょうか？
（盛り上がっている場、ネタが無い場、お酒自体を楽しみたい場等々。方式を選択できる
方が良いでしょうか？）

（蛇足：キャリアさんの元で、SMSなど試験していた身としては、皆さんline好きなんですね
というか何というか、ユーザ視点で満足度が高いのでしょうね。「＋メッセージ」とか今頃
出てもという形でしょうか。）

**Comment by sse01-14** [comment]
完了！
