### ISSUE TITLE
(レコメンド通知) レコメンドを表示する

### ISSUE THREAD

**Issue by sse01-14** [Smart-SE/sse2018-group2#12]

**Comment by ot20161114** [comment]
①タブレットは準備可能でしょうか？
②LINE通知という案も出ましたが、タブレットにはインストールできましたっけ？SIM有りでないと無理でしょうか。無理なら、従業員のモバイルに通知でしょうか？

**Comment by sse01-14** [comment]
@atsuematsu さん
DBにデータを格納しに来る前工程の処理がどうなるか待ちの部分もあるかと思いますが、Raspberry pi上でWebサーバ稼働させてWebブラウザ上でレコメンド表示する処理は特に問題なさそうでしょうか。よくよく考えるとブラウザ側で定期的にリフレッシュ（再読み込み）するような処理をしないと、DBにぬるくなったことがわかるデータが入ってきてもタイムリーにレコメンド表示できないですかね。（デモでは手動リフレッシュでも良い気がしますが）

**Comment by ot20161114** [comment]
Kibanaはオートリフレッシュ（最短５秒）とかしてくれますけどね

https://dandashokai.com/gourmet/1175
（Google Sheetは私はよくわかっておりません。）

基本、ユーザーストーリーを一つ一つこなしていくため、終わっていなければ、
皆さんでつめましょうか（残量検知は捨てる）。出来ていればそれでOK!!:thumbsup:という事で。

**Comment by sse01-14** [comment]
そうですね、金曜来れる方はその時に、最終的には土曜午前で皆でまとめて行きましょう！

**Comment by ot20161114** [comment]
Ansibleで立てれば、”色々と”一石二鳥だったりしますかね（私はまだやっていません）

**Comment by ot20161114** [comment]
オートリロードは、ブラウザ側で拡張機能を使用すれば、可能。但し、タブレットのため、
使用出来ない。websocketで非同期通信させる（obnizでデモしたような形）。

**Comment by sse01-14** [comment]
調査ありがとうございます。何かとすんなりとは行かないですね。デモ段階は手動リロードも視野にいれておきましょうか。

**Comment by ot20161114** [comment]
webサーバーまで行きたかったのですが、何分CPUアーキが異なりますので、pipですんなりインストール出来ず、、、続きは出先で。

**Comment by sse01-14** [comment]
LINEは通知は完了！

**Comment by sse01-14** [comment]
完了！
