### ISSUE TITLE
発表資料作成

### ISSUE THREAD

**Issue by sse01-10** [Smart-SE/sse2018-group2#22]
発表資料作成の検討

**Comment by sse01-10** [comment]
資料、どうしましょう？
まだ活躍できていない・力を発揮できていない方がいれば
積極的にお願いいたします。

**Comment by sse01-14** [comment]
タスク作成ありがとうございます！
ドラフト途中ですが、こんな感じどうでしょう？（半ば課題の息抜きで作成したものですが・・・）
[K1_スマートIoTシステム開発実習_グループ2_draft-v1.pptx](https://github.com/Smart-SE/sse2018-group2/files/2410809/K1_.IoT._.2_draft-v1.pptx)

**Comment by sse01-14** [comment]
表紙に学籍番号＆名前を入れたいと思いますので、こちらで皆様お知らせください！

凡例）
sse01-14　渋谷岳人

**Comment by sse01-10** [comment]
読ませていただきました。仕事が早いですね
統一感があってナイスです！！

sse01-10 植松祥吾

**Comment by ot20161114** [comment]
資料作成ありがとうございます（何か息抜き感が凄く出ていて、好きです）
・重量いけそうでしたら、追記させて下さい。
・KPTは記載するのでしたっけ？
・感想はいれるのでしたっけ（最後？）

lineはiphone等スマホ想定なのですね（ipadに入れてしまいましたが）、、、
ハンディは確かにプロバイトのかたでないときついですね、、、

**Comment by ot20161114** [comment]
木・金あたり教室行こうかな、、、

**Comment by sse01-14** [comment]
ご確認ありがとうございます。ひとまず頂いた範囲での表紙です。（名前の並び順は特に意図を持たせる必要はないかと思うので、学籍番号順とさせてくださいませ）
![03_](https://user-images.githubusercontent.com/43286856/45963563-6512f480-c05e-11e8-9c44-c06eeed3e4b1.png)

**Comment by sse01-14** [comment]
> 木・金あたり教室行こうかな、、、

土曜日午前だけだと不安なので、すり合わせできる部分があればやりたいですね。私は木曜だと19時くらいまでしか居られないのですが、金曜日は18:30以降は何時まででも大丈夫そうです。

あれ、そもそもあそこの営業時間って何時まででしたっけ？？

**Comment by sse01-14** [comment]
> ・重量いけそうでしたら、追記させて下さい。
> ・KPTは記載するのでしたっけ？
> ・感想はいれるのでしたっけ（最後？）
> 
> lineはiphone等スマホ想定なのですね（ipadに入れてしまいましたが）、、、
> ハンディは確かにプロバイトのかたでないときついですね、、、

・重量行けそうなら追記で承知しました！
・KPTの記載は特に言われてないと思いますが（そもそも発表資料自体、PPTでまとめるようにとも明確に言われてないですかね・・・）、過程を示す上では入れていきたいですね。
・感想、、、これも入れておいた方が我々の記録としても良い気がしますね。土曜日の最後の時間にざっくばらんに話して追加しましょうか。
・LINEのiPhoneは個人的なイメージなので、iPad全然ありだと思います。iPad＝卓上タブレット、という想定だと、卓上タブレットにLINE入れるのか、という点が気になったので、バイト個々人にLINE ID発行してiPhone（ハンディターミナル）に表示するという形をイメージしました。ただ店舗で複数アカウント取ればiPad＝卓上タブレットの場合でもLINEでメッセージ表示ありですね。

**Comment by ot20161114** [comment]
・授業以外の平日は20:00までかと
・wikiに感想ページを作成しました（備忘録的にお使い下さい）
・LINEさんのプランに、固定電話でいう内線のようなサービスがあるのか存じ上げませんが、
とりあえず、LINE入りのiPad持っていきます。

（追記）
データ保持の部分ですが、ユーザーストーリーに絡められると良いかと思います。
例えば、データ分析して、暑い日はビールがこれくらい消費されるという事がわかり、発注量が最適化され、在庫切れが発生しない！（実際は今年のような猛暑だと消費が多い訳ではないそうですね）
という利点を書き、但し、今回の期間ではMVPから外れ、データ保持に留まるのような。
つまり、システム側でこういう機能があるから、ではなく、あくまでユーザ側からの要求から始まる
という点を強調した方がよいのでは？という事です。

**Comment by ot20161114** [comment]
お名前だけでしたら、lmsに記載されていますね
https://lms.smartse.jp/course/view.php?id=14#section-3

**Comment by sse01-14** [comment]
> お名前だけでしたら、lmsに記載されていますね
> https://lms.smartse.jp/course/view.php?id=14#section-3

お、こんな記載があったんですね。ありがとうございます！

**Comment by sse01-14** [comment]
> ・授業以外の平日は20:00までかと

講義がないときはあまり遅くまでは使えないんですね。
18:30に着いたとして1時間半か、、、
それでも土曜日午前でまとめ切れなさそうな部分があればすり合わせはしておきたいですね。

**Comment by sse01-14** [comment]
> （追記）
> データ保持の部分ですが、ユーザーストーリーに絡められると良いかと思います。
> 例えば、データ分析して、暑い日はビールがこれくらい消費されるという事がわかり、発注量が最適化され、在庫切れが発生しない！（実際は今年のような猛暑だと消費が多い訳ではないそうですね）
> という利点を書き、但し、今回の期間ではMVPから外れ、データ保持に留まるのような。
> つまり、システム側でこういう機能があるから、ではなく、あくまでユーザ側からの要求から始まる
> という点を強調した方がよいのでは？という事です。

そうなんですよね、タスク分解する段階で切り出したものの振り返ってみたらユーザーストーリーにそういう観点なかったなと思い至りました。検討ステップの趣旨からするとUX起点の要求からスタートした方が収まりは良いので、ユーザーストーリーマッピングに1つ追加しようか。。。傾向分析からの需要予測だと消費者というより店舗観点でのベネフィットかなと思いましたが、品切れにならないという観点ならユーザー要求として定義できそうです。

**Comment by ot20161114** [comment]
制作担当の方にも尋ねてみましたが、「アジャイル回すと、新たなユーザーストーリーが生まれる事が利点である」、との事で、まあそうだなと思いましたので、最初はなくて、最後に追加したでも良いかと思いました。
＃木曜は厳しいので、金曜は行く予定です。

**Comment by sse01-14** [comment]
なるほどー、ありがとうございます。こういう時に実務でアジャイルやっておけば良かったな、と思いますね、、、（そもそも選択権あるかどうかという問題はありますが）
私もできれば金曜日に行きます。できるところはまとめ資料も金曜の内にUpdateしてしまいたく。

**Comment by kh1r0** [comment]
資料作成ありがとうございます。
素晴らしい出来ですね。
よろしくお願いいたします。

sse01-22 小林弘典

**Comment by ot20161114** [comment]
【ご連絡】明日、以下を装備して日本橋に行きます。
・ラズパイ（予備）
・ipad
・重量検知のもろもろ

物品が揃えば、結合試験できるかと思います（集合厳しければ、課題を片付け、高島屋を覗いて急いで帰ります:dash:）

**Comment by sse01-14** [comment]
Updated. すいません、まだ表紙の反映だけですが、、、
![image](https://user-images.githubusercontent.com/43286856/46164181-4b74e580-c2c8-11e8-8a19-fac424d670ba.png)

**Comment by sse01-14** [comment]
私も明日（もう今日ですね、、、）日本橋行こうかと思いますので、それぞれの仕上がり具合を確認させて頂いて資料に反映できればと思っております。

**Comment by sse01-10** [comment]
すみません、温度センサーの植松ですが
業務都合で20:00にも間に合わなさそうです。

早めに上がれればSkypeか何かで参加しようと思いますのでよろしくお願いします。

**Comment by ot20161114** [comment]
お疲れ様です。センサー繋いで、リポのソフトで動くかどうかをお知らせ頂ければ助かります。
私（弊社）も、プレフラの様な素敵な制度は無いため、19:00見込みです。

**Comment by ot20161114** [comment]
https://github.com/Smart-SE/sse2018-group2/projects/4
カンバンページ整理しました。残issues確認にお役立て下さい。

**Comment by sse01-14** [comment]
仕事が長引き20時までに日本橋に到達するのが難しくなってしまいました…
すいませんが明日午前でキャッチアップさせてください。

**Comment by sse01-14** [comment]
Github上に上げて頂いている成果物やコメントはこの後も一通り追って行きます

**Comment by ot20161114** [comment]
@sse01-10 
lmsでskype ID通知させて頂きました。ご参加できるようでしたら、
お待ちしております。

また、PR承認ありがとうございます。
バグあるかと思いますが、しょぼいのは修正・コミットお願いできますでしょうか？

**Comment by ot20161114** [comment]
@sse01-14 
お疲れ様です。資料はdocsフォルダにいれてしまおうかと思います。

**Comment by sse01-14** [comment]
ありがとうございます。10分後くらいならSkype入れそうなんですが、そこでお聞きしたりできますかね？

**Comment by sse01-14** [comment]
閉館時間も迫ってると思うので、無理にでなくて大丈夫です。

**Comment by ot20161114** [comment]
同じく、lmsでskype ID通知させて頂きました。

**Comment by ot20161114** [comment]
確認事項
私からは、webサーバどうしましょう？という点です。
何か画面イメージありましたっけ？

私の方で試していたのは「bottle-websocket」というものなんですが、依存関係のライブラリgeventがPIP、easy_installでも入らなくて、その場合、どうやってインストールしたのか、度忘れしてしまいました。

参照：https://myenigma.hatenablog.com/entry/2015/06/27/112553#bottle%E3%81%A7websocket%E3%82%92%E4%BD%BF%E3%81%A3%E3%81%A6%E9%9D%9E%E5%90%8C%E6%9C%9F%E9%80%9A%E4%BF%A1%E3%82%92%E3%81%99%E3%82%8B%E6%96%B9%E6%B3%95

**Comment by ot20161114** [comment]
日本橋は撤収致します（短い！）

**Comment by sse01-14** [comment]
お疲れ様でした！また明日よろしくお願いします！

**Comment by sse01-10** [comment]
遅くなり申し訳ございません。
@ot20161114 さんありがとうございました。
今からコードの実行を行う予定ですが、
現状ではデータ取得部と判別部は分離していると考えてよいでしょうか？

**Comment by ot20161114** [comment]
デモ想定で、分離しないで取得後→判別のつもりにしました。（処理が抜けていましたら、私のミスです。）
判別がpandasでソート処理という実装ですので、データ増えてくるとどうなんだという気がしますが、調整は必要かもしれません。（データは時系列でソート必要無しと考え、tailだけ取るとか。）
@kh1r0さんは、どういう想定でしたでしょうか？

**Comment by ot20161114** [comment]
@sse01-14
本日はありがとうございました。
そういえば、システム（サービス）名ってありましたっけ？リポ側は、マルチバイトは微妙なので英名にしてしまおうかなと思いましたが、発表資料側はイカした（遡求する）命名をお願い致します！

**Comment by sse01-10** [comment]
@ot20161114 
LineNotify何回かやっているんですが通知飛んで行ったりしていますか？

現状src直下のmain.pyを実行しているのですが、JudgeTemperature.pyへの
参照が無かったので勝手に追加しています。
（実行方法が違っていたらすみません）

**Comment by ot20161114** [comment]
すみません、まだ帰宅途中のため、圏外でして。
もう少々お待ちください。
参照無しは失礼致しました。

**Comment by ot20161114** [comment]
命名案
流行りのカタカナにすると、
ヒヤクル、、、
説明資料では怒りがちな人だったので、
ヒヤコイ、、、

**Comment by kh1r0** [comment]
> 判別がpandasでソート処理という実装ですので、データ増えてくるとどうなんだという気がしますが、調整は必要かもしれません。（データは時系列でソート必要無しと考え、tailだけ取るとか。）
> @kh1r0さんは、どういう想定でしたでしょうか？
お疲れ様です。
tailでもよいかもしれません。
またファイルサイズの肥大化を考えると、最新の温度だけCSVファイルに残すほうが
実装もシンプルになると思います。
明日相談させてください！

**Comment by ot20161114** [comment]
22:04から、合計4件通知が来ていました:clap:

![img_0133](https://user-images.githubusercontent.com/36760280/46225511-70cf2580-c394-11e8-96d6-64474539ea7d.PNG)

**Comment by sse01-14** [comment]
> そういえば、システム（サービス）名ってありましたっけ？リポ側は、マルチバイトは微妙なので英名にしてしまおうかなと思いましたが、発表資料側はイカした（遡求する）命名をお願い致します！

> 命名案
> 流行りのカタカナにすると、
> ヒヤクル、、、
> 説明資料では怒りがちな人だったので、
> ヒヤコイ、、、

良いところにお気付きで・・・皆さん明日の通学の時間にでも考えて来て頂けると助かります！

**Comment by kh1r0** [comment]
思い付きです。

![service_name](https://user-images.githubusercontent.com/43286862/46223296-f3081b80-c38d-11e8-84cd-493232a9e08d.jpg)

**Comment by sse01-14** [comment]
うまい！もう一杯！と言って欲しいｗ

**Comment by sse01-14** [comment]
命名案（英語）
Cool Beer　←直球に『冷たいビール』
One More Beer!　←『もう一杯！』的なニュアンス
Bottoms Up!　←『乾杯』というより『残り飲み干して次行こう！』的なイメージで
Here’s to your beautiful eyes!　←『君の瞳に乾杯！』これだったら日本語の方が刺さるか

**Comment by sse01-14** [comment]
Drunk　←　『酔っ払い』語感があんまり面白くないかも
Smash!　←　Smashedで『酔っ払った』って口語（スラング？）、勢いのある語感
![image](https://user-images.githubusercontent.com/43286856/46223686-fa7bf480-c38e-11e8-8112-2f0a5155b731.png)

**Comment by ot20161114** [comment]
ご検討ありがとうございます。
「呑んだくれ」的な奴は、色々と問題ありそうですね。

Amazonも発注に関するサービスですが、dashやgoなど、語感が大切でしょうか。
というわけで、Bottoms Up!が好きですが、日本人には伝わりづらいでしょうか。

**Comment by ot20161114** [comment]
WEB Server サンプル
https://myenigma.hatenablog.com/entry/2015/06/27/112553
これか

https://qiita.com/okhrn/items/4d3c74563154f191ba16
こちらに乗っているアペリティフから引用

**Comment by sse01-14** [comment]
サービス名投票こちらでお願いします
https://chouseisan.com/s?h=54dfe8a9c18a4d4bb95b0b6968e63ace

**Comment by ikedoh8** [comment]
> 表紙に学籍番号＆名前を入れたいと思いますので、こちらで皆様お知らせください！
> 
> 凡例）
> sse01-14　渋谷岳人

渋谷さん
発表資料どうもありがとうございます。
池戸の学籍番号はsse01-09です。
よろしくお願いいたします。

**Comment by sse01-14** [comment]
後PPTコンテンツ確認をこちらでさせてください！
[K1_スマートIoTシステム開発実習_グループ2_draft-v2.pptx](https://github.com/Smart-SE/sse2018-group2/files/2430118/K1_.IoT._.2_draft-v2.pptx)

**Comment by sse01-14** [comment]
> サービス名投票こちらでお願いします
> https://chouseisan.com/s?h=54dfe8a9c18a4d4bb95b0b6968e63ace

結果発表：
![image](https://user-images.githubusercontent.com/43286856/46239529-95e38880-c3d4-11e8-8c2c-ba732c2eb6b3.png)
**ヒヤコイ** に決定いたしました！

**Comment by sse01-14** [comment]
> サービス名投票こちらでお願いします
> https://chouseisan.com/s?h=54dfe8a9c18a4d4bb95b0b6968e63ace

**ヒヤコイ**で決定いたしました！
![image](https://user-images.githubusercontent.com/43286856/46239750-e6101a00-c3d7-11e8-8a77-880bae3e9f62.png)

**Comment by sse01-14** [comment]
[K1_スマートIoTシステム開発実習_グループ2.pptx](https://github.com/Smart-SE/sse2018-group2/files/2430297/K1_.IoT._.2.pptx)

**Comment by sse01-14** [comment]
完了！
