### ISSUE TITLE
冷えたジョッキを持ってきてもらえる

### ISSUE THREAD

**Issue by sse01-14** [Smart-SE/sse2018-group2#4]

**Comment by ikedoh8** [comment]
定義：ジョッキの代わりグラスを用意し、ビールの代わり、冷たい水を用意する。

**Comment by ikedoh8** [comment]
ジョッキ2個を用意できました。

**Comment by ot20161114** [comment]
ありがとうございます。空の状態で、何gでしょうか？
あと、ユーザーストーリーはアサインするのでしっけ？例えば、タスクの外形ではないでしょうか？

**Comment by sse01-14** [comment]
このユーザーストーリー分のタスク作成してなかったですね・・・
以下タスクでお願いします！
#13

**Comment by ikedoh8** [comment]
奥田さん

お疲れ様です。池戸です。
実はジョッキ2個を先週土曜日に日本橋NEOに置きました。重さを測る為本日新規調達しました。
ご参考に 、 空の状態で、340g前後です。
宜しくお願いします。

2018年9月23日(日) 16:53 Takao Okuda <notifications@github.com>:

**Comment by ot20161114** [comment]
お手数おかけして申し訳ございません。承知しました。
では、日本橋に行けば、デモ出来るという事ですね。

**Comment by sse01-14** [comment]
完了！
