### ISSUE TITLE
(温度検知) センサを決定する

### ISSUE THREAD

**Issue by sse01-14** [Smart-SE/sse2018-group2#6]

**Comment by ot20161114** [comment]
obniz想定

**Comment by ot20161114** [comment]
obniz.js パーツライブラリに対応しているものに変更して良いでしょうか？
手持ちにLM35DZ（Arduinoエントリーキットに入っているもの）がありました。
https://obniz.io/sdk/parts/LM35DZ/README.md?iframe=false

防水をどうするか、、、

**Comment by sse01-14** [comment]
obnizでさくっとデータ取れそうに見えたので良いのではないかと思いました。
防水については、試作段階ではプラスチックカップを２段重ねにして２重底の部分にセンサを入れる（＝内側のカップの底の温度を外側から測る形）なんてどうでしょう？

**Comment by ot20161114** [comment]
ご確認ありがとうございます。（私の理解が疎く、イメージがまだあまり出来ていません）

https://obniz.io/sdk/parts/LM35DZ/README.md?iframe=false
現状の直挿しのみですと、↑のonchangeのTest Runを実行して頂けるとわかるかと思いますが、
表示が高めにばたついて出力されます。

以下の方と同様のようです。
https://edycube.blog.fc2.com/blog-entry-1056.html
https://edycube.blog.fc2.com/blog-entry-1057.html
コンデンサ等で調整が必要なようです。

なお、冷えたペットボトルに当てたところ、少しは下がりましたが、部屋の温度より少し下ぐらいでした。

**Comment by ot20161114** [comment]
そもそも、液体の温度を測るには、以下のようなものが必要でしょうか？（いずれも距離があってよいので、raspberry piから引いてよいかと思います。）
①非接触赤外線温度センサ
　TMP006、TMP007、GY-906（MLX90614）等
参考：https://edycube.blog.fc2.com/blog-entry-963.html
②ステンレス鋼管防水温度センサ
　DS18B20等
参考：
https://www.amazon.co.jp/dp/B074V4W4DX/ref=sspa_dk_detail_2?psc=1&pd_rd_i=B074V4W4DX&pf_rd_m=AN1VRQENFRJN5&pf_rd_p=c26608a3-d22f-4d1b-893c-df18c784b79e&pf_rd_r=MEAE9XK18W5FMA6CTQQ5&pd_rd_wg=gqjY5&pf_rd_s=desktop-dp-sims&pf_rd_t=40701&pd_rd_w=lNb3J&pf_rd_i=desktop-dp-sims&pd_rd_r=85246b43-baea-11e8-bf86-d515babdeeb8
https://www.amazon.co.jp/UMEMOTO-%E9%98%B2%E6%B0%B4%E5%9E%8B-%E6%B8%A9%E5%BA%A6%E3%82%BB%E3%83%B3%E3%82%B5%E3%83%BC-DS18B20%E4%BA%92%E6%8F%9B/dp/B0082MYD06
https://www.robotshop.com/jp/ja/ds18b20-waterproof-digital-temperature-sensor.html

**Comment by sse01-14** [comment]
LM35DZの取り扱いがなかなか難しそうですね、、、冷えたビール、という前提で言えば氷を入れて冷やすぐらいまでやっても良いのかもしれませんが、それで妥当な挙動が得られるかは気になりますね。

**Comment by sse01-14** [comment]
＞①非接触赤外線温度センサ
なるほど、放射温度計で非接触計測って良いですね。ただ私も専門的な知識があるわけではないのですが、以下のページなんかを見ると赤外光の入射角度や照射範囲の調整が結構シビアなようなので、ジョッキの位置を上手く合わせないといけないのかなと感じました。
https://ureruzo.com/ondo-hInfo.htm

**Comment by sse01-10** [comment]
最も取りやすそうなのはやはり、直接水に入れて測定できる"②ステンレス鋼管防水温度センサ"
になりそうですね。。。
精度も±0.5℃なので十分と思います。

**Comment by sse01-14** [comment]
そうっすねー、ビールの温度を直接図るならこれが一番ダイレクトで良いですよね。後はジョッキの中にこれが入っていても違和感がない感じにできたらベストですが、、、想像すると気になってしまいそう(笑)

**Comment by sse01-14** [comment]
とは言えデモの段階ではそこまで気にしなくても良いかもしれないですね。センサーの選定パターンとしては以下3つがあるところまで洗い出していて、コンセプト検証の段階では一番実現し易い(a)でデモします、と言ってしまっても良いのかなと考えました。

(a) ビールそのものの温度を測る（防水温度センサ）
(b) ジョッキの外側の温度を直接測る（温度センサ）
(c)  ジョッキの外側の温度を間接的に測る （非接触赤外線温度センサ）

**Comment by sse01-10** [comment]
(a) ビールそのものの温度を測る（防水温度センサ）
防水の利点を生かしてジョッキにそのままくっつければある程度は測れるかもしれないですね。
試してみる価値はありそうです。

変わった方法として、水センサというものがありました。
水にぬれると電位が下がってそれを検知するそうです。
ビールを提供してしばらくすると結露して水が垂れるのを利用するという手も・・（・・無いか。）
https://www.switch-science.com/catalog/817/

**Comment by ot20161114** [comment]
> ご確認ありがとうございます。（私の理解が疎く、イメージがまだあまり出来ていません）
> 
> https://obniz.io/sdk/parts/LM35DZ/README.md?iframe=false
> 現状の直挿しのみですと、↑のonchangeのTest Runを実行して頂けるとわかるかと思いますが、
> 表示が高めにばたついて出力されます。
> 
> 以下の方と同様のようです。
> https://edycube.blog.fc2.com/blog-entry-1056.html
> https://edycube.blog.fc2.com/blog-entry-1057.html
> コンデンサ等で調整が必要なようです。
> 
> なお、冷えたペットボトルに当てたところ、少しは下がりましたが、部屋の温度より少し下ぐらいでした。

https://web.obniz.io/2018/08/01/vcc-noise-reduction-of-first-version-of-obniz/
センサというより、obniz側の構造上（内部ADC）の問題のようです。
とりあえず、USBアダプタ変更すると、10回に1回、正しい値が出ているように思います。
（尼のレビューで、センサ側が文句言われてましたが、とばっちりといいますか、、、）

**Comment by ot20161114** [comment]
help議論ありがとうございます！
結局、デバイスの方が全て担当するような形になってしまいそうですが、
では、どなたか防水温度センサ、、、お持ちではないと思いますが、用意して実装していただける方いらっしゃいますでしょうか？（修了制作で関連がある等）＃不衛生を承知で

obnizで物理設計とソフト設計分離できるかと思いましたが、そうもいかなそうで。

私の方は、残量検知をトライしてみようかと思っています。
※LM35DZも以下のイメージ（例はコーヒーですが）で、もうちょっと頑張ってみようかと思います。
https://speakerdeck.com/shanonim/mei-wei-siikohifalseyin-miqing-wojiao-etekureruiot

**Comment by ot20161114** [comment]
放射温度計は、確かに、対象物からすると角度・視野がシビアですね。
私がみたのは、以下です。
https://edycube.blog.fc2.com/blog-entry-963.html

**Comment by sse01-14** [comment]
私は修了制作が実装系ではないので防水温度センサを使う予定はないのですが、値段からすれば割り勘で買ってしまうのもありかなと思います。obniz使わないのであればデータ処理コンポーネントへのデータ受け渡しはひとまず有線ってことになりますかね。

**Comment by sse01-10** [comment]
私も温度センサは使う予定はありませんが、
AmazonのDS18B20を買って作ってみます。
…ラズパイで良いですよね…？？

下記を参考にしようと思います。
https://yamashitakoji.com/2016/05/raspberry-pi-ds18b20.html

**Comment by ot20161114** [comment]
ありがとうございます！
ラズパイで良いと思います。
参考はpythonですが、jsなら、web化しやすいのではないでしょうか？モジュールもありそうです。
ご参考：
https://github.com/kolarcz/node-w1temp

**Comment by ot20161114** [comment]
方針が出ましたので、クローズ致します。
