### ISSUE TITLE
(温度検知) データ取得方法を決定する

### ISSUE THREAD

**Issue by sse01-14** [Smart-SE/sse2018-group2#7]

**Comment by sse01-10** [comment]
決めるべきこと
利用するセンサのハードウェア設計（回路など）

**Comment by sse01-10** [comment]
obnize利用不可の場合
・Raspberry pi +DHT11（授業ではGR-sakuraで利用）
ピン
　１番：5V
　２番：GPIO
　３番：NC（Non-Connected = 使用していない）
　４番：GND
抵抗
　10kΩ

下記を見る限り、ADコンバータは不要な模様

https://camo.qiitausercontent.com/c4d15b71b8d1ff45987aa72c14ec26479bf4295e/68747470733a2f2f71696974612d696d6167652d73746f72652e73332e616d617a6f6e6177732e636f6d2f302f34333333302f63333264323263392d653830372d313130362d643063662d3638303136363338623337352e706e67

**Comment by sse01-10** [comment]
優先的
・obnizの場合
　回路＋温度センサ一体型

**Comment by sse01-14** [comment]
現状はDS18B20＋ラズパイって方向になっていますが、後工程での使い方を考慮すると、
①温度情報＋デバイスIDも取得したい
②①の結果をCSVファイルで吐き出しておきたい
って話になっているのですが、できそうなもんですかね？データ取得する時間間隔は特に議論になっていませんが、最初は5秒とか10秒とか適当で良いかなとは思っています。

**Comment by sse01-10** [comment]
①温度情報＋デバイスIDも取得したい
②①の結果をCSVファイルで吐き出しておきたい
を実装してcodeに置いておきました。

待ちはしてませんが"main.py"の下のコメントを外してもらえば
ある程度操作はできるはずです。

**Comment by ot20161114** [comment]
ファイルを読んで取得出来るのですね。
値もデジタルなので、安定しているといいますか。
ぬるくなるを再現するのは時間的に厳しいので、離してしまうしかないでしょうか。

**Comment by sse01-14** [comment]
Great!!
@kh1r0 さん、後工程のデータ処理行けそうですかね？

**Comment by sse01-14** [comment]
＞ぬるくなるを再現するのは時間的に厳しいので
そうっすね、ジョッキ2個（&保冷剤）を用意して頂いたので、片方は常温、片方は冷やした状態で、センサ差し替えて疑似的にぬるくなった状態を再現する感じかなと思ってます。

**Comment by kh1r0** [comment]
CSVファイルの吐き出しありがとうございます。
後工程のデータ処理実装してみます。

**Comment by ot20161114** [comment]
リポの配置・Readmeを修正してもよろしいでしょうか？
（個人としては、フォークしておいてもらえれば。あれ、sse01-10さんはグループ３を
フォークしている？？？）

**Comment by kh1r0** [comment]
はい。おまかせします。

**Comment by ot20161114** [comment]
ありがとうございます。とりあえず、現状の作業を、wikiに退避します。

**Comment by ot20161114** [comment]
https://github.com/Smart-SE/sse2018-group2/pull/23
ファイル統合案となります。Pythonの構文当たりは問題無いかと思いますが、
通した訳では無く、エイヤの部分もございますので、コメント頂ければと思います。

**Comment by sse01-14** [comment]
完了！
