### ISSUE TITLE
(温度検知) データ処理コンポーネントとのIF・通信方法の決定

### ISSUE THREAD

**Issue by sse01-14** [Smart-SE/sse2018-group2#8]

**Comment by sse01-10** [comment]
#7領域と認識を誤っていたため転記

利用するデバイス：
　・raspberry pi
　(・Arduino)

通信方式：
　・有線 シリアル通信（暫定的）
　・無線 BLE

センサ側：
　・上記通信方式に準拠

**Comment by ikedoh8** [comment]
定義：　下記の通りです。

利用するデバイス：
　・raspberry pi
　(・Arduino)

通信方式：
　・有線 シリアル通信（デモ環境）
　・無線 BLE（本番環境）

センサ側：
　・上記通信方式に準拠

**Comment by sse01-14** [comment]
9/22の議論で、デモ段階では以下とする方針。

利用するデバイス：
Raspberry pi

センサ～Raspberry pi（データ取得）間の通信方式：
有線直結
データ形式としては温度情報＋デバイスID（できれば）

Raspberry pi（データ取得）～データ処理コンポーネント間の通信：
データ処理コンポーネントもRaspberry piを使用する想定
→1台のRaspberry pi上でデータ取得もデータ処理もそのまま行う

**Comment by sse01-14** [comment]
サービス化段階ではBluetoothを想定。
デモ段階では上記コメントの通り有線接続とする方針となったため、本タスクはクローズとする。
